---
title: "wk7_prac_coding"
author: "chris"
date: "2021/11/24"
output: html_document
---

7.4.1 Setting up your Data
```{r library}
library(tidyverse)
library(tmap)
library(geojsonio)
library(plotly)
library(rgdal)
library(broom)
library(mapview)
library(crosstalk)
library(sf)
library(sp)
library(spdep)
library(car)
library(fs)
library(janitor)
```

```{r}
#download a zip file containing some boundaries we want to use

download.file("https://data.london.gov.uk/download/statistical-gis-boundary-files-london/9ba8c833-6370-4b11-abdc-314aa020d5e0/statistical-gis-boundaries-london.zip", 
              destfile="data/statistical-gis-boundaries-london.zip")
```

```{r}
#Get the zip file and extract it
listfiles<-dir_info(here::here("data")) %>%
  dplyr::filter(str_detect(path, ".zip")) %>%
  dplyr::select(path)%>%
  pull()%>%
  #print out the .gz file
  print()%>%
  as.character()%>%
  utils::unzip(exdir=here::here("data"))
```
```{r}
#look what is inside the zip

Londonwards<-dir_info(here::here("data", 
                                 "statistical-gis-boundaries-london", 
                                 "ESRI"))%>%
  #$ means exact match
  dplyr::filter(str_detect(path, 
                           "London_Ward_CityMerged.shp$"))%>%
  dplyr::select(path)%>%
  pull()%>%
  #read in the file in
  st_read()
```

```{r}
#check the data
qtm(Londonwards)
```

```{r}
#We can use readr to deal with the issues in this dataset - which are to do with text values being stored in columns containing numeric values

#read in some data - couple of things here. Read in specifying a load of likely 'n/a' values, also specify Latin1 as encoding as there is a pound sign (£) in one of the column headers - just to make things fun!

LondonWardProfiles <- read_csv("https://data.london.gov.uk/download/ward-profiles-and-atlas/772d2d64-e8c6-46cb-86f9-e52b4c7851bc/ward-profiles-excel-version.csv", 
                               na = c("", "NA", "n/a"), 
                               locale = locale(encoding = 'Latin1'), 
                               col_names = TRUE)
```

```{r}
#check all of the columns have been read in correctly
Datatypelist <- LondonWardProfiles %>% 
  clean_names()%>%
  summarise_all(class) %>%
  pivot_longer(everything(), 
               names_to="All_variables", 
               values_to="Variable_class")

Datatypelist
```
```{r}
#merge boundaries and data
LonWardProfiles <- Londonwards%>%
  left_join(.,
            LondonWardProfiles,
            by=c('GSS_CODE'='New code'))
```

```{r}
#map our dependent variable to see if the join has worked
tmap_mode('plot')
qtm(LonWardProfiles,
    fill="Average GCSE capped point scores - 2014",
    borders = NULL,
    fill.palette='Blues')

```
7.4.1.2 Additional Data
```{r}
#might be a good idea to see where the secondary schools are in London too
london_schools <- read_csv('https://data.london.gov.uk/download/london-schools-atlas/57046151-39a0-45d9-8dc0-27ea7fd02de8/all_schools_xy_2016.csv')

#from the coordinate values stored in the x and y columns, which look like they are latitude and longitude values, create a new points dataset
lon_school_sf <- st_as_sf(london_schools,
                          coords=c('x','y'),
                          crs=4326)

lon_sec_schools_sf <- lon_school_sf%>%
  clean_names()%>%
  filter(phase=='Secondary')

tmap_mode('plot')
qtm(lon_sec_schools_sf)
```

